server:
  port: 8091

spring:
  # mysql连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.95.10.24:3306/cq?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: xroot
  cq:
    # 在这里配置各个功能执行顺序
    # 如果前一个功能返回MESSAGE_BLOCK，下一个功能不会被执行
    # 如果前一个功能返回MESSAGE_IGNORE，会继续执行下一个功能
    plugin-list:
      - com.huangyichun.auto_cq.plugin.MainPlugin
      - com.huangyichun.auto_cq.plugin.TestPlugin
      - com.huangyichun.auto_cq.plugin.HelloPlugin

    # 下面配置event线程池，也可以删掉用默认的
    event:
      core-pool-size: 5
      max-pool-size: 20
      keep-alive-time: 2000
      work-queue-size: 256
    # 还有一些其他配置可以自己探索

# bilibi 插件设置
bilibili:
  png-save-path: C:/tempPNG/
  chrome-driver-path: C:/modules/chrome/chromedriver_win83.exe